name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: true
      #    tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-congreso:latest

      #- name: conectar via ssh y desplegar usando compose productivo sobre archivo productivo
      #  uses: appleboy/ssh-action@v0.1.5
      #  with:
      #    host: ${{ secrets.DEPLOY_HOST }}
      #    username: ${{ secrets.DEPLOY_USERNAME }}
      #    key: ${{ secrets.DEPLOY_PASSWORD }}
      #    port: 22
      #    script: |
      #      cd /home/app-politicos
      #      docker compose   -f docker-compose.prod.yml up  app -d --build


      - name: install ssh keys
          # check this thread to understand why its needed:
          # https://stackoverflow.com/a/70447517
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAo2U/Ef9PhsbbuUbB/bsEIROzh5HuDSK07Ng8eBqaUGelgnNZFbuG
IwxSR6+VRjEFEQasIh1Vr8EQVfHQ9MJSMyJU5QDfLWubEuQ1FW8N1OFkSGImKR6A7kn8L/
vWtraWQ/a6gKPhw3zaPo/NPB1Sb62Q8HOfXkIsdNdh+LZCnwwS+Ek5Pk/2pJHsuAC438ef
65k7fEuqv5b4zVdzFD1choZHyq3YxazduyyoecMgn2ozPTDcndqfsYyjusO4e3+YQI3juq
OLKInwEcZGg/xHeKqUN5LMC4OfjDfa6Fesitm9iU72iVU+rLt9EiawHfH7oCD9OXUY6deQ
1GEFuW13kXLrhpn1bqoTHlAmJKqsPyFYq2y3NWJQYTqqqjsjVhNJEUoP3gdXN3FAoZOo36
nWCRpAE3U6yu3GaIaBueByCPFyt1Pv+ZkX2g2TVi/PGpVLn3MCY1lEegGKVUsTZXg14UWN
ywVyUjGuMFPigMblshwzQZ/2l3DOEslL75Gthv1tQ8jo7CvwavA+GR0BAEkz+VbChqJcnR
kSyAIIjLoHwiCn74tNNkoY7zThcgMP+sQjVy0t5VnxXN1wD97WxwPO8S4mtCd7nQPYzjS1
RhZbOYcKgRBQD6DAuYapLdDhbVI0++DtgI6NZNMCWGbsxACDXYXXi70ZBZSO3fo25pZZd5
sAAAdYgjyT54I8k+cAAAAHc3NoLXJzYQAAAgEAo2U/Ef9PhsbbuUbB/bsEIROzh5HuDSK0
7Ng8eBqaUGelgnNZFbuGIwxSR6+VRjEFEQasIh1Vr8EQVfHQ9MJSMyJU5QDfLWubEuQ1FW
8N1OFkSGImKR6A7kn8L/vWtraWQ/a6gKPhw3zaPo/NPB1Sb62Q8HOfXkIsdNdh+LZCnwwS
+Ek5Pk/2pJHsuAC438ef65k7fEuqv5b4zVdzFD1choZHyq3YxazduyyoecMgn2ozPTDcnd
qfsYyjusO4e3+YQI3juqOLKInwEcZGg/xHeKqUN5LMC4OfjDfa6Fesitm9iU72iVU+rLt9
EiawHfH7oCD9OXUY6deQ1GEFuW13kXLrhpn1bqoTHlAmJKqsPyFYq2y3NWJQYTqqqjsjVh
NJEUoP3gdXN3FAoZOo36nWCRpAE3U6yu3GaIaBueByCPFyt1Pv+ZkX2g2TVi/PGpVLn3MC
Y1lEegGKVUsTZXg14UWNywVyUjGuMFPigMblshwzQZ/2l3DOEslL75Gthv1tQ8jo7Cvwav
A+GR0BAEkz+VbChqJcnRkSyAIIjLoHwiCn74tNNkoY7zThcgMP+sQjVy0t5VnxXN1wD97W
xwPO8S4mtCd7nQPYzjS1RhZbOYcKgRBQD6DAuYapLdDhbVI0++DtgI6NZNMCWGbsxACDXY
XXi70ZBZSO3fo25pZZd5sAAAADAQABAAACAAyZ7T3+L2WicxiilQ+niCwXrZO9IYHm1TnW
e8qUqdkD0IQAHfTRaqKYu5HAWb+5KrEpwnjt3TyTcNouYfvP+4nqns4VSqD7BWsoD9LKDU
pUYnXVblvJq/TbEaiogGJeY4L06/5DmIPWK0WCG2ueJH9TZsDi+EpkyeWHvnKkqWLdvTeW
+7CxqkDLHKZpYj8NhLWLsq0L1hMCwC5wWgIyF0j5FMYg5GQEyHCI6aqP7c8Nk2UOBL2x08
YPWPAGHyiuUJFawAWvwWnMQltq+LSkh+VakAxXKG0s5s803lxnD2Bn/+uVtbXytCvOWKXf
ncG5dof4QCWmjiTR4kWjmk7qJ9UZA3rp0bNMKfvXWMXAztj+GsinCUYZrRF5ywr9drToxD
bYa22QppBMUblMXtcMOTWD/5uHloT/jw5rRbvmkjTyCP0005nrBzE0uO5OLYfMqUBpkqll
V2M9mXzl4hJDSbdgc+sppwRdWv2Xp0Me3qfODZztXYIz4KiQFH9tWE8AbAE9jnb9QYvK2C
uRF7RV1vyq9tW+/0648lp/nVH7Szvnb+2NVaA/YbkgxbW4BapczGqRgFalJH8uXC/Ii82v
8z88Dh5xjOR27xDQth0lzh/Dcy8cb+8COpSRw8djsuU/vYibWnrfSfuiB/DFfgB00Sy1Z/
JpNC7WeTjN0qgVG4NtAAABADd3WASfONvTz+YnJvB2jWBrt5Q6xtGQX7LWnxNVkQqGYhI+
luyS1LMqus5cgrHVnQM9OmwS/Axf8Ekg6psMT9qFSmj+MmbmDrXQaowExjbIURXqeZdbm+
hENDQp9WKmA8W2ERCLKm0kvLBXLoxDP2HycNovfOYkssy7C+DjThJ+l3Prl/FODSJAkJY7
DR41BffTV8ZPE8+mH9xmWiOUxtnVN0q94ed5EV/Vgo2D+/a3Mvwpb5haLDToBB4g5BR+jl
eR4u4uDq64Z0lLjUP1/6SFO5tGZtvSsTDrL3X2XLpheowpXcbtTF5dSZkgYnVFjN8vKdBN
6gxVzG0rgBnXJuAAAAEBAOIB9k/hJwy/OJUfiaGNtMR0lo3LxHghm8J3IFCEWGbawxuvyp
ZjFKKJX7Sk/QSHpsZahKxuJfy/gAjLSPDYB5SiBN+cvl4uPRBuD6amvbyjsY2BSGlM++wh
3Lfol1QGCCYXyZQCaco721x50WKpIQowbJomeC4TmfxbYEoRyN6b3f6hdnahh7ztpZ5HJ/
JMzI9SHmQz7d+yXLPNqS0tGzDH5NmvMun8HSFMQexv4dCSfNGaBQq33jYFB9MVEjmLoB4M
OPxQ0UmhSsuITimCYYria5Ya0cNDLK3qXWvVCr5ubDSP+0HhIT5B4Kqc+aeCxZYkZJJ3XS
EbfJR2eZC74Q0AAAEBALkUMb8IyAd3MzvK3ntpLZ7DK96yDDr0rFqr5Nut8v93F7H+3o27
Q4ShCpZHqLq31dWj8w+08iX39mXo2W57/9x3bfWt+9HqKeGMtiCVf8913kPClkj28PvRe9
AYd7bgEO45cVXarVKD566RBNyY5dKNBCs0vWaOGbk9JahAcE92OskF00XXTjwAq/82DCWl
E4w4EuVhznULIeumK7NJV7OitIpImmSWIb0sC0jV4NvC7VsKWBUU1pMHLtjhJJeQ0SBIjB
zSP7MCARWq6V9bnQEjXDgVC9XINVI/P9neQCyKs2MhmG/GjNm+Uzm3nDb5X+SlKu1gMNvJ
XCCqybaRAUcAAAAfcm9vdEB1YnVudHUtcy0ydmNwdS0yZ2Itc2ZvMy0wMQECAwQ=
" > ~/.ssh/id_rsa
            #ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} > ~/.ssh/known_hosts
            ssh-keyscan -H 143.198.64.143  > ~/.ssh/known_hosts           
      - name: connect and deploy
        #run: ssh ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }} "cd /home/app-politicos &&  docker compose -f docker-compose.prod.yml up app -d --build  && exit"
        run: ssh root@143.198.64.143 "cd /home/app-politicos &&  docker compose -f docker-compose.prod.yml up app -d --build  && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
